version: '3.3'

services:
  app:
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./code:/code
      - ./static:/static
    command: python manage.py runserver 0.0.0.0:8000