# Generated by Django 4.0.4 on 2022-04-18 01:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessLoan',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('currency', models.CharField(choices=[('USD', 'US Dollars'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('AUD', 'Australian Dollar')], max_length=4)),
                ('loan_value', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100000), django.core.validators.MinValueValidator(10000)])),
                ('loan_length_in_days', models.IntegerField(default=180)),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('business_name', models.CharField(max_length=100, null=True)),
                ('business_address', models.CharField(max_length=100, null=True)),
                ('company_number', models.IntegerField(null=True)),
                ('business_sector_name', models.CharField(choices=[('1', 'Retail'), ('2', 'Professional'), ('3', 'Services'), ('4', 'Food_and_Drink'), ('5', 'Entertainment')], default='5', max_length=2)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
