# Generated by Django 4.0.4 on 2022-04-18 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_alter_business_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='author',
        ),
        migrations.AddField(
            model_name='business',
            name='userid',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
