# Generated by Django 4.0.4 on 2022-04-18 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_business_author_business_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='userid',
            new_name='author',
        ),
    ]
