# Generated by Django 3.2.19 on 2023-05-14 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('card_name', models.CharField(max_length=100)),
                ('qr_code', models.CharField(max_length=100)),
                ('card_image', models.ImageField(upload_to='cards/')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
