# Generated by Django 3.2.20 on 2023-07-11 01:43

import cryptocons.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CardsModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('leprechaun_number', models.CharField(max_length=10)),
                ('tier', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('validation_code', models.IntegerField(default=cryptocons.models.generate_random_number)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
