# Generated by Django 3.2.19 on 2023-05-14 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocons', '0002_cards_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cards',
            old_name='card_image',
            new_name='image_location',
        ),
    ]
